feat: Added MiniPlaceholders support
ArcanePlugins/PAPISigns pull request #2
Opened 2023-06-06 16:34 UTC by 4drian3d

resolves #1

2023-06-07 11:36 UTC, lokka30 requested changes
Awesome, thank you! I have a few tiny changes to recommend.

2023-06-07 11:36 UTC, lokka30 commented on src/main/java/com/mrivanplays/papisigns/loader/PapiSigns.java
> +        getLogger().info("Using "+placeholderProvider+" as PlaceholderProvider");
```suggestion
        getLogger().info("Using " + placeholderProvider + " as PlaceholderProvider");
```

2023-06-07 11:36 UTC, lokka30 commented on src/main/java/com/mrivanplays/papisigns/loader/PapiSigns.java
> +        getLogger().info("No Placeholder Provider plugin found. Disabling plugin.");
```suggestion
        getLogger().warning("No compatible placeholder provider plugin found; disabling plugin.");
```

2023-06-07 13:48 UTC, lokka30 approved these changes

2023-06-07 14:23 UTC, MrIvanPlays requested changes
Seems good overall, however I'd like some sort of priority system.
For example what if a server has both MiniPlaceholders and PlaceholderAPI? Which one is going to be prioritized? 

Let's consider that a server runs both MP and PAPI. In that case, we also need a system to distinguish whether a placeholder is a MP or PAPI one.

Please let me know whether you can implement these stuff. If you can't I'm gonna merge this as-is and implement such systems.

2023-06-07 15:07 UTC, 4drian3d commented
> Seems good overall, however I'd like some sort of priority system. For example what if a server has both MiniPlaceholders and PlaceholderAPI? Which one is going to be prioritized?
> 
> Let's consider that a server runs both MP and PAPI. In that case, we also need a system to distinguish whether a placeholder is a MP or PAPI one.
> 
> Please let me know whether you can implement these stuff. If you can't I'm gonna merge this as-is and implement such systems.

Currently MiniPlaceholders integration would be prioritized, if someone wanted to use PlaceholderAPI placeholders they could use the https://github.com/MiniPlaceholders/PlaceholderAPI-Expansion expansion.
This could not be done from PlaceholderAPI, that's why I prioritized the MiniPlaceholders integration, since PlaceholderAPI has string placeholders, while MiniPlaceholders has component placeholders.
Nor could you do a multiparse between multiple placeholder integrations because it would be quite resource intensive as it would serialize and deserialize components multiple times, in an event as heavy as the PlayerMoveEvent

2023-06-07 15:12 UTC, MrIvanPlays approved these changes

2023-06-07 15:13 UTC, merged

2023-06-08 01:59 UTC, lokka30 commented
Sweet - thanks for your contribution @4drian3d!